#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : datefudge
Version  : 1.22
Release  : 2
URL      : http://http.debian.net/debian/pool/main/d/datefudge/datefudge_1.22.tar.xz
Source0  : http://http.debian.net/debian/pool/main/d/datefudge/datefudge_1.22.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: datefudge-bin
Requires: datefudge-lib
Requires: datefudge-license
Requires: datefudge-man
Patch1: build.patch

%description
All files in this repository / Debian archive are (c) 2002-2003
by Matthias Urlichs <smurf@noris.de>. They are licensed under the Gnu
Public License, version 2, included as the file "COPYING".

%package bin
Summary: bin components for the datefudge package.
Group: Binaries
Requires: datefudge-license = %{version}-%{release}
Requires: datefudge-man = %{version}-%{release}

%description bin
bin components for the datefudge package.


%package doc
Summary: doc components for the datefudge package.
Group: Documentation
Requires: datefudge-man = %{version}-%{release}

%description doc
doc components for the datefudge package.


%package lib
Summary: lib components for the datefudge package.
Group: Libraries
Requires: datefudge-license = %{version}-%{release}

%description lib
lib components for the datefudge package.


%package license
Summary: license components for the datefudge package.
Group: Default

%description license
license components for the datefudge package.


%package man
Summary: man components for the datefudge package.
Group: Default

%description man
man components for the datefudge package.


%prep
%setup -q -n datefudge-1.22
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1537842773
make  %{?_smp_mflags}

%install
export SOURCE_DATE_EPOCH=1537842773
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/datefudge
cp COPYING %{buildroot}/usr/share/doc/datefudge/COPYING
cp debian/copyright %{buildroot}/usr/share/doc/datefudge/debian_copyright
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/datefudge

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/datefudge/debian_copyright

%files lib
%defattr(-,root,root,-)
/usr/lib64/datefudge/datefudge.so

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/datefudge/COPYING

%files man
%defattr(-,root,root,-)
/usr/share/man/man1/datefudge.1
